name: create release

on:
  workflow_call:
    inputs:
      public_name:
        required: true
        type: string
        description: 'the name the user can see'
      internal_name:
        required: true
        type: string
        description: 'the assembly name'
      project_dir:
        required: true
        type: string
        description: 'folder containing csproj'
      project_name:
        required: true
        type: string
        description: 'csproj file name'
      version_change:
        required: true
        type: string
        description: 'what type of release this is (MAJOR, MINOR, PATCH)'
      new_version:
        required: true
        type: string
        description: 'the new version for this release (e.g. 3.4.5)'
      github_username:
        required: true
        type: string
        description: 'gitHub username for commits'
      github_email:
        required: true
        type: string
        description: 'gitHub email for commits'
      force_push:
        required: false
        type: boolean
        description: 'force push the version change commit?'
        default: false
    secrets: 
      REPO_TOKEN:
        required: true
    outputs:
      release_sha:
        description: 'the commit sha for this release'
        value: ${{ jobs.create-release.outputs.release_sha }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      PUBLIC_NAME: ${{ inputs.public_name }}
      INTERNAL_NAME: ${{ inputs.internal_name }}
      PROJECT_DIR: ${{ inputs.project_dir }}
      PROJECT_NAME: ${{ inputs.project_name }}
      VERSION_CHANGE: ${{ inputs.version_change }}
      NEW_VERSION: ${{ inputs.new_version }}
      GITHUB_USERNAME: ${{ inputs.github_username }}
      GITHUB_EMAIL: ${{ inputs.github_email }}
      FORCE_PUSH: ${{ inputs.force_push }}
      CSPROJ_PATH: ${{ inputs.project_dir }}/${{ inputs.project_name }}.csproj
    outputs:
      release_sha: ${{ steps.capture-sha.outputs.release_sha }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: set up git
      run: |
        git config --global user.name "${GITHUB_USERNAME}"
        git config --global user.email "${GITHUB_EMAIL}"
        echo "git configuration set for author: ${GITHUB_USERNAME} <${GITHUB_EMAIL}>"

    - name: update .csproj version
      run: |
        ORIG_VERSION="$(sed -nE 's:<Version>([^<]*)</Version>:\1:p' "$CSPROJ_PATH")"
        echo "ORIG_VERSION=$ORIG_VERSION" >> $GITHUB_ENV
        sed -i "s:<Version>[^<]*</Version>:<Version>$NEW_VERSION</Version>:" "$CSPROJ_PATH"
        echo "updated .csproj version at $CSPROJ_PATH from $ORIG_VERSION to $NEW_VERSION"

    - name: commit .csproj changes
      run: |
        git add "$PROJECT_DIR/$PROJECT_NAME.csproj"
        git commit -m "[release] v${NEW_VERSION} (${VERSION_CHANGE})"
        echo "committed .csproj changes."

    - name: push .csproj version change
      run: |
        ref="HEAD:${{ github.ref_name }}"
        if [[ $FORCE_PUSH == true ]]; then
          echo "force pushing: $ref"
          ref="+$ref"
        else
          echo "pushing: $ref"
        fi
        git push origin "$ref"
        echo "pushed .csproj version changes to the repository."

    - name: tag release
      run: |
        git tag "$NEW_VERSION" HEAD
        git push origin "$NEW_VERSION"
        echo "tagged release."
        
    - name: capture release sha
      id: capture-sha
      run: |
        release_sha="$(git rev-parse HEAD)"
        echo "release_sha=$release_sha" >> $GITHUB_OUTPUT
        echo "**release sha**: $release_sha" >> $GITHUB_STEP_SUMMARY
