name: deploy plugin

on:
  workflow_call:
    inputs:
      deployment_type:
        required: true
        type: string
        description: 'stable or testing'
      public_name:
        required: true
        type: string
        description: 'the name the user can see'
      internal_name:
        required: true
        type: string
        description: 'the assembly name'
      project_name:
        required: false
        type: string
        description: 'csproj file name (only relevant when deployment_type is `testing`)'
      project_repo:
        required: false
        type: string
        description: 'repo of the plugin project (only relevant when deployment_type is `testing`)'
      release_sha:
        required: false
        type: string
        description: 'the full sha for the plugin commit to release (only relevant when deployment_type is `testing`)'
      release_version:
        required: true
        type: string
        description: 'the version being deployed, e.g. 1.2.6'
      owners:
        required: false
        type: string
        description: 'the plugin owners, comma separated (only relevant when deployment_type is `testing`)'
      open_pr:
        required: false
        type: boolean
        description: 'open pull request?'
        default: false
      github_username:
        required: true
        type: string
        description: 'github username for commits'
      github_email:
        required: true
        type: string
        description: 'github email for commits'
    secrets:
      REPO_TOKEN:
        required: true
        
env:
  PUBLIC_NAME: ${{ inputs.public_name }}
  INTERNAL_NAME: ${{ inputs.internal_name }}
  PROJECT_NAME: ${{ inputs.project_name }}
  PROJECT_REPO: ${{ inputs.project_repo }}
  OWNERS: ${{ inputs.owners }}
  RELEASE_SHA: ${{ inputs.release_sha }}
  RELEASE_VERSION: ${{ inputs.release_version }}
  DEPLOYMENT_TYPE: ${{ inputs.deployment_type }}
  GITHUB_USERNAME: ${{ inputs.github_username }}
  GITHUB_EMAIL: ${{ inputs.github_email }}
  DEPLOY_PATH_STABLE: stable/${{ inputs.internal_name }}
  DEPLOY_PATH_LIVE: testing/live/${{ inputs.internal_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: validate inputs
      run: |
        if [[ "$DEPLOYMENT_TYPE" != "testing" && "$DEPLOYMENT_TYPE" != "stable" ]]; then
          echo "deployment_type must be one of: [testing, stable]"
          exit 1
        fi
        
        if [[ "$DEPLOYMENT_TYPE" == "testing" ]]; then
          if [[ -z "$RELEASE_SHA" ]]; then
            echo "release_sha is required for deployment_type 'testing', but was empty"
            exit 1
          fi
          if [[ -z "$RELEASE_VERSION" ]]; then
            echo "release_version is required for deployment_type 'testing', but was empty"
            exit 1
          fi
        fi

    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: configure git
      run: |
        git config --global user.name "${GITHUB_USERNAME}"
        git config --global user.email "${GITHUB_EMAIL}"
        echo "git configuration set for author: ${GITHUB_USERNAME} <${GITHUB_EMAIL}>"

    - name: configure deploy branch
      run: |
        BRANCH=$(echo "${PUBLIC_NAME}/${DEPLOYMENT_TYPE}" | tr '[:upper:]' '[:lower:]' | tr ' ' _)
        echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"
        
        echo "> fetching goat main branch..."
        git remote add goat https://github.com/goatcorp/DalamudPluginsD17.git
        git fetch goat main
        
        if git show-ref --quiet "refs/heads/${BRANCH}"; then
            echo "> branch ${BRANCH} already exists. deleting..."
            git branch -D "${BRANCH}"
        fi
        echo "> creating branch ${BRANCH} from goat/main..."
        git checkout -b "${BRANCH}" goat/main
        git push --set-upstream origin "+${BRANCH}:${BRANCH}"
        echo "> branch setup complete for ${BRANCH}."

    - name: compute deploy path
      run: |
        if [[ "${DEPLOYMENT_TYPE}" == "stable" ]]; then
          echo "DEPLOY_PATH=$DEPLOY_PATH_STABLE" >> $GITHUB_ENV
        else
          echo "DEPLOY_PATH=$DEPLOY_PATH_LIVE" >> $GITHUB_ENV
        fi

    - name: create plugin manifest directory
      run: |
        if [[ ! -d "$DEPLOY_PATH" ]]; then
          mkdir -p "$DEPLOY_PATH"
          echo "created manifest directory for $INTERNAL_NAME $DEPLOYMENT_TYPE."
        else
          echo "manifest directory exists."
        fi

    - name: copy plugin manifest from testing to stable
      if: inputs.deployment_type == 'stable'
      run: |
        rm -r "$DEPLOY_PATH_STABLE"
        cp -r "$DEPLOY_PATH_LIVE" "$DEPLOY_PATH_STABLE"
        echo "copied manifest from testing to stable."

    - name: create plugin TOML manifest
      if: inputs.deployment_type != 'stable'
      run: |
        cd "$DEPLOY_PATH"
        if [[ -f manifest.toml ]]; then
          echo "deleting existing manifest..."
        fi
        echo "[plugin]" > manifest.toml
        echo "repository = \"${{ github.server_url }}/${PROJECT_REPO}.git\"" >> manifest.toml
        echo "owners = [ \"${OWNERS//,/\", \"}\" ]" >> manifest.toml
        echo "project_path = \"$PROJECT_NAME\"" >> manifest.toml
        echo "commit = \"$RELEASE_SHA\"" >> manifest.toml
        echo "created manifest.toml:"
        cat manifest.toml

    - name: add and commit changes
      run: |
        cd "$DEPLOY_PATH"
        if [[ "$DEPLOYMENT_TYPE" == "stable" ]]; then
          COMMIT_MESSAGE="Promote $PUBLIC_NAME v$RELEASE_VERSION to Stable"
        else
          COMMIT_MESSAGE="[Testing] $PUBLIC_NAME v$RELEASE_VERSION"
        fi
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        git add manifest.toml
        git commit -m "$COMMIT_MESSAGE"
        echo "added and committed all changes with message: $COMMIT_MESSAGE"

    - name: push changes
      run: |
        set -x
        ls .git/refs/heads 
        git branch -av
        git push -v origin "+${BRANCH}:${BRANCH}"
        echo "pushed changes to branch: ${BRANCH}"

    - name: open a pull request
      if: inputs.open_pr == true
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          const response = github.rest.pulls.create({
            owner: "goatcorp",
            repo: "DalamudPluginsD17",
            base: "main",
            head: "${{ github.repository_owner }}:${{ env.BRANCH }}",
            title: "${{ env.COMMIT_MESSAGE }}",
          });
          
          console.log(response);

    - name: done
      run: echo "deploy $DEPLOYMENT_TYPE done"
